### ISSUE TITLE
optimizer 服务运行一段时间以后出现内存不足提示

### ISSUE THREAD

**Issue by walteryang47** [eayun/EayunOS-optimizer#4]
optimizer 服务运行一段时间以后， 在 /var/log/ovirt-optimizer/ovirt-optimizer.log 中会出现如下错误信息：

```
14:51:07,964 ERROR [stderr] (Thread-2641) Exception in thread "Thread-2641" java.lang.OutOfMemoryError: GC overhead limit exceeded
14:51:12,157 ERROR [stderr] (Thread-1082) Exception in thread "Thread-1082" java.lang.OutOfMemoryError: GC overhead limit exceeded
14:51:16,825 ERROR [stderr] (Thread-120) Exception in thread "Thread-120" java.lang.OutOfMemoryError: GC overhead limit exceeded
14:51:21,321 ERROR [stderr] (Thread-1328) Exception in thread "Thread-1328" java.lang.OutOfMemoryError: GC overhead limit exceeded
14:51:37,749 ERROR [org.quartz.core.JobRunShell] (oVirtOptimizerScheduler_Worker-2) Job DEFAULT.6da64b5bd2ee-51a5eb6d-ea0f-4e35-a337-21ccd3500b58 threw an unhandled Exception: : java.lang.OutOfMemoryError: GC overhead limit exceeded

14:51:37,749 ERROR [org.quartz.core.ErrorLogger] (oVirtOptimizerScheduler_Worker-2) Job (DEFAULT.6da64b5bd2ee-51a5eb6d-ea0f-4e35-a337-21ccd3500b58 threw an exception.: org.quartz.SchedulerException: Job threw an unhandled exception. [See nested exception: java.lang.OutOfMemoryError: GC overhead limit exceeded]
    at org.quartz.core.JobRunShell.run(JobRunShell.java:218) [quartz-2.2.0.jar:]
    at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:560) [quartz-2.2.0.jar:]
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
```

初步判断为由于jvm运行参数的 Xmx 指定的值太小，导致内存不足，垃圾回收机制一直运行但回收不了多少内存。如果把 Xmx 的值调大，会影响 appliance 的内存不足。

需要一个解决办法。

**Comment by walteryang47** [comment]
经测试，确实是 optimizer 服务本身需要大量的内存资源（Xmx 1g 也不够用），用 jstat 查看 optimizer 的 jvm 内存使用信息，基本都占满：

```
# jps -v
1643 -- process information unavailable
1508 -- process information unavailable
2051 -- process information unavailable
17966 jboss-modules.jar -XX:+TieredCompilation -Xms256m -Xmx1g -XX:PermSize=128m -XX:MaxPermSize=256m -Djava.net.preferIPv4Stack=true -Dsun.rmi.dgc.client.gcInterval=3600000 -Dsun.rmi.dgc.server.gcInterval=3600000 -Djava.awt.headless=true -Djava.util.logging.manager=org.jboss.logmanager -Dorg.jboss.resolver.warning=true -Djboss.modules.system.pkgs=org.jboss.byteman -Djboss.modules.write-indexes=false -Djboss.server.default.config=ovirt-optimizer -Djboss.home.dir=/usr/share/ovirt-engine-jboss-as -Djboss.server.config.dir=/etc/ovirt-optimizer

# jstat -gc 17966 1000
 S0C    S1C    S0U    S1U      EC       EU        OC         OU       PC     PU    YGC     YGCT    FGC    FGCT     GCT   
1024.0 1024.0  0.0    0.0   347648.0 347648.0  698880.0   698548.4  131072.0 76207.2 121091  668.541 3063  1803.863 2472.404
1024.0 1024.0  0.0    0.0   347648.0 347648.0  698880.0   698548.4  131072.0 76207.2 121091  668.541 3064  1804.474 2473.016
1024.0 1024.0  0.0    0.0   347648.0 272899.1  698880.0   698548.4  131072.0 76207.2 121091  668.541 3065  1805.693 2474.235
1024.0 1024.0  0.0    0.0   347648.0 347648.0  698880.0   698548.4  131072.0 76207.2 121091  668.541 3067  1806.312 2474.853
1024.0 1024.0  0.0    0.0   347648.0 347648.0  698880.0   698548.4  131072.0 76207.2 121091  668.541 3068  1806.980 2475.521
1024.0 1024.0  0.0    0.0   347648.0 347648.0  698880.0   698548.4  131072.0 76207.2 121091  668.541 3069  1807.600 2476.141
1024.0 1024.0  0.0    0.0   347648.0 347648.0  698880.0   698548.4  131072.0 76207.2 121091  668.541 3070  1808.208 2476.749
1024.0 1024.0  0.0    0.0   347648.0 176335.4  698880.0   698548.4  131072.0 76207.2 121091  668.541 3071  1809.481 2478.023
1024.0 1024.0  0.0    0.0   347648.0 347648.0  698880.0   698548.4  131072.0 76207.2 121091  668.541 3073  1810.124 2478.665
1024.0 1024.0  0.0    0.0   347648.0 347648.0  698880.0   698548.4  131072.0 76207.2 121091  668.541 3074  1810.736 2479.278
1024.0 1024.0  0.0    0.0   347648.0 347648.0  698880.0   698548.4  131072.0 76207.2 121091  668.541 3075  1811.339 2479.880
1024.0 1024.0  0.0    0.0   347648.0 72562.7   698880.0   698548.4  131072.0 76207.2 121091  668.541 3076  1812.590 2481.131
1024.0 1024.0  0.0    0.0   347648.0 317166.8  698880.0   698548.4  131072.0 76207.2 121091  668.541 3077  1813.167 2481.708
1024.0 1024.0  0.0    0.0   347648.0 347648.0  698880.0   698548.4  131072.0 76207.2 121091  668.541 3079  1813.732 2482.273
1024.0 1024.0  0.0    0.0   347648.0 347648.0  698880.0   698548.4  131072.0 76207.2 121091  668.541 3080  1814.392 2482.934
1024.0 1024.0  0.0    0.0   347648.0 347648.0  698880.0   698548.4  131072.0 76207.2 121091  668.541 3081  1814.967 2483.508
1024.0 1024.0  0.0    0.0   347648.0 347648.0  698880.0   698548.4  131072.0 76207.2 121091  668.541 3082  1815.541 2484.082
```

**Comment by walteryang47** [comment]
经过测试，调整 /etc/ovirt-optimizer/ovirt-optimizer.properties 里的 org.ovirt.optimizer.solver.steps 参数来减少对内存资源的使用， 该参数用于计算最优的迁移步骤的步骤数量上限（步骤越多，资源消耗呈非线性增长）。需要提供一个目前 appliance 合理的参数设置。

**Comment by walteryang47** [comment]
使用 org.ovirt.optimizer.solver.steps=15 的参数运行一小时后 jvm 的内存使用正常。故先用这个参数，继续测试。 已在 commit： c38ce5309b6f6da2ae65a31b6658d5565983d3d1 中包含该改动。

```
# jstat -gc 11486 1000
 S0C    S1C    S0U    S1U      EC       EU        OC         OU       PC     PU    YGC     YGCT    FGC    FGCT     GCT   
512.0  512.0  288.0   0.0   348672.0 245137.0  175104.0   156374.2  151552.0 70036.7   3432   11.994   3      0.730   12.725
512.0  512.0  352.0   0.0   348672.0 212395.1  175104.0   157014.2  151552.0 70036.7   3438   12.014   3      0.730   12.744
512.0  512.0  384.0   0.0   348672.0 198981.8  175104.0   157590.2  151552.0 70036.7   3444   12.032   3      0.730   12.763
512.0  512.0  256.0   0.0   348672.0   0.0     175104.0   158158.2  151552.0 70036.7   3450   12.051   3      0.730   12.781
512.0  512.0   0.0   352.0  348672.0 64694.7   175104.0   158598.2  151552.0 70036.7   3455   12.069   3      0.730   12.799
512.0  512.0   0.0   352.0  348672.0 52437.1   175104.0   159142.3  151552.0 70036.7   3461   12.091   3      0.730   12.821
512.0  512.0   0.0   256.0  348672.0   0.0     175104.0   159838.3  151552.0 70036.7   3467   12.113   3      0.730   12.843
512.0  512.0  288.0   0.0   348672.0 272249.4  175104.0   160318.3  151552.0 70036.7   3472   12.131   3      0.730   12.862
512.0  512.0  352.0   0.0   348672.0 114713.7  175104.0   160766.4  151552.0 70036.7   3478   12.153   3      0.730   12.883
512.0  512.0  288.0   0.0   348672.0   0.0     175104.0   161314.4  151552.0 70042.7   3484   12.177   3      0.730   12.908
512.0  512.0   0.0   256.0  348672.0 233868.5  175104.0   161738.4  151552.0 70042.7   3489   12.195   3      0.730   12.926
512.0  512.0   0.0   320.0  348672.0 200760.3  175104.0   162214.4  151552.0 70042.7   3495   12.215   3      0.730   12.945
512.0  512.0   0.0   288.0  348672.0 50566.4   175104.0   162762.4  151552.0 70042.7   3501   12.237   3      0.730   12.967
512.0  512.0   0.0   320.0  348672.0 34917.3   175104.0   163286.4  151552.0 70042.7   3507   12.257   3      0.730   12.988
512.0  512.0   0.0   384.0  348672.0   0.1     175104.0   163722.5  151552.0 70042.7   3513   12.278   3      0.730   13.008
512.0  512.0  256.0   0.0   348672.0 69297.8   175104.0   164146.5  151552.0 70042.7   3518   12.296   3      0.730   13.027
512.0  512.0   0.0   416.0  348672.0 220704.7  175104.0   164622.5  151552.0 70042.7   3523   12.314   3      0.730   13.045
512.0  512.0   0.0   320.0  348672.0 30685.2   175104.0   165202.5  151552.0 70042.7   3529   12.334   3      0.730   13.065
512.0  512.0   0.0   352.0  348672.0   0.0     175104.0   165630.5  151552.0 70042.7   3535   12.356   3      0.730   13.086
512.0  512.0  288.0   0.0   348672.0 184873.4  175104.0   166046.5  151552.0 70042.7   3540   12.375   3      0.730   13.106
512.0  512.0  288.0   0.0   348672.0 116468.9  175104.0   166578.5  151552.0 70042.7   3546   12.399   3      0.730   13.129
512.0  512.0   0.0   352.0  348672.0 224688.2  175104.0   166982.6  151552.0 70042.7   3551   12.417   3      0.730   13.148
512.0  512.0   0.0   192.0  348672.0 34458.5   175104.0   167238.6  151552.0 70042.7   3555   12.430   3      0.730   13.161
512.0  512.0  160.0   0.0   348672.0 200859.4  175104.0   167246.6  151552.0 70042.7   3556   12.434   3      0.730   13.165
512.0  512.0  160.0   0.0   348672.0 200884.9  175104.0   167246.6  151552.0 70042.7   3556   12.434   3      0.730   13.165
512.0  512.0  160.0   0.0   348672.0 200918.9  175104.0   167246.6  151552.0 70042.7   3556   12.434   3      0.730   13.165
512.0  512.0  160.0   0.0   348672.0 201117.8  175104.0   167246.6  151552.0 70042.7   3556   12.434   3      0.730   13.165
512.0  512.0  160.0   0.0   348672.0 201150.2  175104.0   167246.6  151552.0 70042.7   3556   12.434   3      0.730   13.165
512.0  512.0  160.0   0.0   348672.0 201207.9  175104.0   167246.6  151552.0 70042.9   3556   12.434   3      0.730   13.165
512.0  512.0  160.0   0.0   348672.0 201209.9  175104.0   167246.6  151552.0 70042.9   3556   12.434   3      0.730   13.165
512.0  512.0  160.0   0.0   348672.0 201212.0  175104.0   167246.6  151552.0 70042.9   3556   12.434   3      0.730   13.165
512.0  512.0  160.0   0.0   348672.0 201212.0  175104.0   167246.6  151552.0 70042.9   3556   12.434   3      0.730   13.165
```

**Comment by walteryang47** [comment]
运行一天以后发现 jvm 的 heap 内存仍然被占满，reopen

**Comment by walteryang47** [comment]
通过 dump optimizer 的 jvm 运行时内存分析后发现，主要是 optaplanner 的 DefaultSolver 占用了大部分内存（90%以上）。见下图：
![memdump](https://cloud.githubusercontent.com/assets/7271300/7025032/5c8c1b60-dd73-11e4-82b6-09cb65b38d68.jpg)
目前不确定具体原因，需要深入研究。目前采用当内存不足时重启的 workaround 办法，
具体见 commit: 5d310e3ca0defb11005d51d41e70dc00b4c393b3  。
