### ISSUE TITLE
optimizer 内存不足而重启后服务端口绑定失败

### ISSUE THREAD

**Issue by walteryang47** [eayun/EayunOS-optimizer#6]
此问题由 eayun/EayunOS-optimizer#4 引起，当重启是有如下信息：

```
#
# java.lang.OutOfMemoryError: GC overhead limit exceeded
# -XX:OnOutOfMemoryError="service ovirt-optimizer restart"
#   Executing /bin/sh -c "service ovirt-optimizer restart"...
Stopping ovirt optimizer service: [  OK  ]^M
Starting ovirt optimizer service:                 [  ^[[32mOK^[[0m  ]
14:48:43,181 INFO  [org.jboss.as.security] (ServerService Thread Pool -- 26) JBAS013101: Activating Security Subsystem
14:48:43,187 INFO  [org.jboss.as.naming] (ServerService Thread Pool -- 22) JBAS011800: Activating Naming Subsystem
14:48:43,216 INFO  [org.jboss.as.webservices] (ServerService Thread Pool -- 30) JBAS015537: Activating WebServices Extension
14:48:43,292 INFO  [org.jboss.as.security] (MSC service thread 1-4) JBAS013100: Current PicketBox version=4.0.7.Final
14:48:43,325 INFO  [org.jboss.as.connector] (MSC service thread 1-3) JBAS010408: Starting JCA Subsystem (JBoss IronJacamar 1.0.9.Final)
14:48:43,349 INFO  [org.jboss.as.naming] (MSC service thread 1-6) JBAS011802: Starting Naming Service
14:48:43,503 INFO  [org.jboss.ws.common.management.AbstractServerConfig] (MSC service thread 1-7) JBoss Web Services - Stack CXF Server 4.0.2.GA
14:48:43,574 ERROR [org.apache.coyote.http11.Http11Protocol] (MSC service thread 1-8) Error initializing endpoint: java.net.BindException: Address already in use /0.0.0.0:8330
        at org.apache.tomcat.util.net.JIoEndpoint.init(JIoEndpoint.java:983) [jbossweb-7.0.13.Final.jar:]
        at org.apache.coyote.http11.Http11Protocol.init(Http11Protocol.java:190) [jbossweb-7.0.13.Final.jar:]
        at org.apache.catalina.connector.Connector.init(Connector.java:983) [jbossweb-7.0.13.Final.jar:]
        at org.jboss.as.web.WebConnectorService.start(WebConnectorService.java:267) [jboss-as-web-7.1.1.Final.jar:7.1.1.Final]
        at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1811) [jboss-msc-1.0.2.GA.jar:1.0.2.GA]
        at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1746) [jboss-msc-1.0.2.GA.jar:1.0.2.GA]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [rt.jar:1.7.0_75]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [rt.jar:1.7.0_75]
        at java.lang.Thread.run(Thread.java:745) [rt.jar:1.7.0_75]
...
JBAS014777:   Services which failed to start:      service jboss.serverManagement.controller.management.http: org.jboss.msc.service.StartException in service jboss.serverManagement.controller.management.http: Address already in use /127.0.0.1:10240
      service jboss.remoting.server.remoting-connector: org.jboss.msc.service.StartException in service jboss.remoting.server.remoting-connector: JBAS017112: Address already in use /0.0.0.0:4697
      service jboss.remoting.server.management: org.jboss.msc.service.StartException in service jboss.remoting.server.management: JBAS017112: Address already in use /127.0.0.1:10249
      service jboss.web.connector.http: org.jboss.msc.service.StartException in service jboss.web.connector.http: JBAS018007: Error starting web connector

```

**Comment by walteryang47** [comment]
finxed by: 04c0d1d840ff03fb0ec202815386fde2b672ab3e
